[package]
name = "aoc-2024"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"

[dependencies]
colored = "2.0.0"
rand = "0.8.5"
regex = "1.10.2"
image = "0.25.5"
